database:
    # This can be either postgresql, mysql or sqlite
    type: sqlite

    sqlite:
        path: ":memory:"

    database: localhost:5432
    host: scheduledb
    username: postgres
    password: postgres