database:
    # This can be either postgresql, mysql or sqlite
    type: sqlite

    sqlite:
        path: ":memory:"

    database: scheduledb
    host: localhost:5432
    username: postgres
    password: postgres