database:
    # This can be either postgresql, mysql or sqlite
    type: sqlite

    sqlite:
        # Leave this empty for non-persistent storage
        path: ""

    database: scheduledb
    host: localhost:5432
    username: postgres
    password: postgres